# Generated by Django 5.2.13 on 2026-05-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_announcement'),
        ('reports', '0004_report_reported_images_alter_report_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('type', models.CharField(choices=[('PHOTO', 'Photo'), ('SKETCH', 'Sketch'), ('MEDICAL', 'Medical'), ('REPORT', 'Report')], max_length=20)),
                ('description', models.TextField()),
                ('uploaded_by', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='documentation/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentations', to='reports.report')),
            ],
        ),
    ]
