# Generated by Django 5.2.13 on 2026-05-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_documentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='additional_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
