# Generated by Django 5.2.13 on 2026-05-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_documentation_additional_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('action', models.CharField(choices=[('CASE_EDITED', 'Case edited'), ('DOC_UPLOADED', 'Document uploaded'), ('LOGIN', 'Login'), ('CASE_CREATED', 'New case created'), ('ACCOUNT_UPDATED', 'Account updated'), ('ANNOUNCEMENT_CREATED', 'Announcement created'), ('DOC_DELETED', 'Document deleted')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
