# Generated by Django 5.2.13 on 2026-04-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField()),
                ('incident_type', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_address', models.CharField(max_length=255)),
                ('vehicles_involved', models.IntegerField(default=0)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('description', models.TextField()),
                ('plate_numbers', models.CharField(blank=True, max_length=255, null=True)),
                ('injured_count', models.IntegerField(default=0)),
                ('reporter_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=50)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('reporter_role', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Review', 'In Review'), ('Open', 'Open'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_filed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
