# Generated by Django 5.2.13 on 2026-04-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='report',
            name='incident_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
