# Generated by Django 5.2.13 on 2026-04-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Review', 'In Review'), ('Closed', 'Closed'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='ReportImage',
        ),
    ]
